// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: with_composite_id.proto

package schema

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// EntityWithCompositeId
type EntityWithCompositeId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFirstPart  string               `protobuf:"bytes,1,opt,name=id_first_part,json=idFirstPart,proto3" json:"id_first_part,omitempty"`     // part of composite primary key
	IdSecondPart uint32               `protobuf:"varint,2,opt,name=id_second_part,json=idSecondPart,proto3" json:"id_second_part,omitempty"` // part of composite primary key
	IdThirdPart  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=id_third_part,json=idThirdPart,proto3" json:"id_third_part,omitempty"`     // part of composite primary key
	Name         string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Value        int32                `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EntityWithCompositeId) Reset() {
	*x = EntityWithCompositeId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_with_composite_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityWithCompositeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityWithCompositeId) ProtoMessage() {}

func (x *EntityWithCompositeId) ProtoReflect() protoreflect.Message {
	mi := &file_with_composite_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityWithCompositeId.ProtoReflect.Descriptor instead.
func (*EntityWithCompositeId) Descriptor() ([]byte, []int) {
	return file_with_composite_id_proto_rawDescGZIP(), []int{0}
}

func (x *EntityWithCompositeId) GetIdFirstPart() string {
	if x != nil {
		return x.IdFirstPart
	}
	return ""
}

func (x *EntityWithCompositeId) GetIdSecondPart() uint32 {
	if x != nil {
		return x.IdSecondPart
	}
	return 0
}

func (x *EntityWithCompositeId) GetIdThirdPart() *timestamp.Timestamp {
	if x != nil {
		return x.IdThirdPart
	}
	return nil
}

func (x *EntityWithCompositeId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityWithCompositeId) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// EntityCompositeId - container for composite primary key
type EntityCompositeId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFirstPart  string               `protobuf:"bytes,1,opt,name=id_first_part,json=idFirstPart,proto3" json:"id_first_part,omitempty"`
	IdSecondPart uint32               `protobuf:"varint,2,opt,name=id_second_part,json=idSecondPart,proto3" json:"id_second_part,omitempty"`
	IdThirdPart  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=id_third_part,json=idThirdPart,proto3" json:"id_third_part,omitempty"`
}

func (x *EntityCompositeId) Reset() {
	*x = EntityCompositeId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_with_composite_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityCompositeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityCompositeId) ProtoMessage() {}

func (x *EntityCompositeId) ProtoReflect() protoreflect.Message {
	mi := &file_with_composite_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityCompositeId.ProtoReflect.Descriptor instead.
func (*EntityCompositeId) Descriptor() ([]byte, []int) {
	return file_with_composite_id_proto_rawDescGZIP(), []int{1}
}

func (x *EntityCompositeId) GetIdFirstPart() string {
	if x != nil {
		return x.IdFirstPart
	}
	return ""
}

func (x *EntityCompositeId) GetIdSecondPart() uint32 {
	if x != nil {
		return x.IdSecondPart
	}
	return 0
}

func (x *EntityCompositeId) GetIdThirdPart() *timestamp.Timestamp {
	if x != nil {
		return x.IdThirdPart
	}
	return nil
}

// EntityWithCompositeIdList
type EntityWithCompositeIdList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*EntityWithCompositeId `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *EntityWithCompositeIdList) Reset() {
	*x = EntityWithCompositeIdList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_with_composite_id_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityWithCompositeIdList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityWithCompositeIdList) ProtoMessage() {}

func (x *EntityWithCompositeIdList) ProtoReflect() protoreflect.Message {
	mi := &file_with_composite_id_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityWithCompositeIdList.ProtoReflect.Descriptor instead.
func (*EntityWithCompositeIdList) Descriptor() ([]byte, []int) {
	return file_with_composite_id_proto_rawDescGZIP(), []int{2}
}

func (x *EntityWithCompositeIdList) GetItems() []*EntityWithCompositeId {
	if x != nil {
		return x.Items
	}
	return nil
}

// CreateEntityWithCompositeId
type CreateEntityWithCompositeId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFirstPart  string               `protobuf:"bytes,1,opt,name=id_first_part,json=idFirstPart,proto3" json:"id_first_part,omitempty"`
	IdSecondPart uint32               `protobuf:"varint,2,opt,name=id_second_part,json=idSecondPart,proto3" json:"id_second_part,omitempty"`
	IdThirdPart  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=id_third_part,json=idThirdPart,proto3" json:"id_third_part,omitempty"`
	Name         string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Value        int32                `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CreateEntityWithCompositeId) Reset() {
	*x = CreateEntityWithCompositeId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_with_composite_id_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEntityWithCompositeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntityWithCompositeId) ProtoMessage() {}

func (x *CreateEntityWithCompositeId) ProtoReflect() protoreflect.Message {
	mi := &file_with_composite_id_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntityWithCompositeId.ProtoReflect.Descriptor instead.
func (*CreateEntityWithCompositeId) Descriptor() ([]byte, []int) {
	return file_with_composite_id_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEntityWithCompositeId) GetIdFirstPart() string {
	if x != nil {
		return x.IdFirstPart
	}
	return ""
}

func (x *CreateEntityWithCompositeId) GetIdSecondPart() uint32 {
	if x != nil {
		return x.IdSecondPart
	}
	return 0
}

func (x *CreateEntityWithCompositeId) GetIdThirdPart() *timestamp.Timestamp {
	if x != nil {
		return x.IdThirdPart
	}
	return nil
}

func (x *CreateEntityWithCompositeId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEntityWithCompositeId) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// UpdateEntityWithCompositeId
type UpdateEntityWithCompositeId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdFirstPart  string               `protobuf:"bytes,1,opt,name=id_first_part,json=idFirstPart,proto3" json:"id_first_part,omitempty"`
	IdSecondPart uint32               `protobuf:"varint,2,opt,name=id_second_part,json=idSecondPart,proto3" json:"id_second_part,omitempty"`
	IdThirdPart  *timestamp.Timestamp `protobuf:"bytes,3,opt,name=id_third_part,json=idThirdPart,proto3" json:"id_third_part,omitempty"`
	Name         string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Value        int32                `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateEntityWithCompositeId) Reset() {
	*x = UpdateEntityWithCompositeId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_with_composite_id_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEntityWithCompositeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntityWithCompositeId) ProtoMessage() {}

func (x *UpdateEntityWithCompositeId) ProtoReflect() protoreflect.Message {
	mi := &file_with_composite_id_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntityWithCompositeId.ProtoReflect.Descriptor instead.
func (*UpdateEntityWithCompositeId) Descriptor() ([]byte, []int) {
	return file_with_composite_id_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEntityWithCompositeId) GetIdFirstPart() string {
	if x != nil {
		return x.IdFirstPart
	}
	return ""
}

func (x *UpdateEntityWithCompositeId) GetIdSecondPart() uint32 {
	if x != nil {
		return x.IdSecondPart
	}
	return 0
}

func (x *UpdateEntityWithCompositeId) GetIdThirdPart() *timestamp.Timestamp {
	if x != nil {
		return x.IdThirdPart
	}
	return nil
}

func (x *UpdateEntityWithCompositeId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEntityWithCompositeId) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_with_composite_id_proto protoreflect.FileDescriptor

var file_with_composite_id_proto_rawDesc = []byte{
	0x0a, 0x17, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65,
	0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xcb, 0x01, 0x0a, 0x15, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x57, 0x69, 0x74,
	0x68, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d,
	0x69, 0x64, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x64, 0x46, 0x69, 0x72, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74,
	0x12, 0x24, 0x0a, 0x0e, 0x69, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x70, 0x61,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x69, 0x64, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x50, 0x61, 0x72, 0x74, 0x12, 0x3e, 0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x74, 0x68, 0x69,
	0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x69, 0x64, 0x54, 0x68, 0x69,
	0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x9d, 0x01, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69,
	0x64, 0x46, 0x69, 0x72, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x64,
	0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x69, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x12, 0x3e, 0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0b, 0x69, 0x64, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x22, 0x50, 0x0a, 0x19, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x33, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x57, 0x69, 0x74, 0x68,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x70,
	0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x64, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x64, 0x5f, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x69, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x74, 0x12, 0x3e, 0x0a, 0x0d,
	0x69, 0x64, 0x5f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0b, 0x69, 0x64, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xd1, 0x01, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x57, 0x69, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69,
	0x64, 0x46, 0x69, 0x72, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x64,
	0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x69, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x12, 0x3e, 0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0b, 0x69, 0x64, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_with_composite_id_proto_rawDescOnce sync.Once
	file_with_composite_id_proto_rawDescData = file_with_composite_id_proto_rawDesc
)

func file_with_composite_id_proto_rawDescGZIP() []byte {
	file_with_composite_id_proto_rawDescOnce.Do(func() {
		file_with_composite_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_with_composite_id_proto_rawDescData)
	})
	return file_with_composite_id_proto_rawDescData
}

var file_with_composite_id_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_with_composite_id_proto_goTypes = []interface{}{
	(*EntityWithCompositeId)(nil),       // 0: schema.EntityWithCompositeId
	(*EntityCompositeId)(nil),           // 1: schema.EntityCompositeId
	(*EntityWithCompositeIdList)(nil),   // 2: schema.EntityWithCompositeIdList
	(*CreateEntityWithCompositeId)(nil), // 3: schema.CreateEntityWithCompositeId
	(*UpdateEntityWithCompositeId)(nil), // 4: schema.UpdateEntityWithCompositeId
	(*timestamp.Timestamp)(nil),         // 5: google.protobuf.Timestamp
}
var file_with_composite_id_proto_depIdxs = []int32{
	5, // 0: schema.EntityWithCompositeId.id_third_part:type_name -> google.protobuf.Timestamp
	5, // 1: schema.EntityCompositeId.id_third_part:type_name -> google.protobuf.Timestamp
	0, // 2: schema.EntityWithCompositeIdList.items:type_name -> schema.EntityWithCompositeId
	5, // 3: schema.CreateEntityWithCompositeId.id_third_part:type_name -> google.protobuf.Timestamp
	5, // 4: schema.UpdateEntityWithCompositeId.id_third_part:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_with_composite_id_proto_init() }
func file_with_composite_id_proto_init() {
	if File_with_composite_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_with_composite_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityWithCompositeId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_with_composite_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityCompositeId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_with_composite_id_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityWithCompositeIdList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_with_composite_id_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEntityWithCompositeId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_with_composite_id_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEntityWithCompositeId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_with_composite_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_with_composite_id_proto_goTypes,
		DependencyIndexes: file_with_composite_id_proto_depIdxs,
		MessageInfos:      file_with_composite_id_proto_msgTypes,
	}.Build()
	File_with_composite_id_proto = out.File
	file_with_composite_id_proto_rawDesc = nil
	file_with_composite_id_proto_goTypes = nil
	file_with_composite_id_proto_depIdxs = nil
}
