// Code generated by protoc-gen-go. DO NOT EDIT.
// source: with_indexes.proto

package schema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EntityWithIndexes
type EntityWithIndexes struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// one external id
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// required multiple external ids (minimum 1)
	RequiredExternalIds []string `protobuf:"bytes,3,rep,name=required_external_ids,json=requiredExternalIds,proto3" json:"required_external_ids,omitempty"`
	// optional multiple external ids (minimum 0)
	OptionalExternalIds  []string `protobuf:"bytes,4,rep,name=optional_external_ids,json=optionalExternalIds,proto3" json:"optional_external_ids,omitempty"`
	Value                int32    `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntityWithIndexes) Reset()         { *m = EntityWithIndexes{} }
func (m *EntityWithIndexes) String() string { return proto.CompactTextString(m) }
func (*EntityWithIndexes) ProtoMessage()    {}
func (*EntityWithIndexes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22c1b92282e067, []int{0}
}

func (m *EntityWithIndexes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityWithIndexes.Unmarshal(m, b)
}
func (m *EntityWithIndexes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityWithIndexes.Marshal(b, m, deterministic)
}
func (m *EntityWithIndexes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityWithIndexes.Merge(m, src)
}
func (m *EntityWithIndexes) XXX_Size() int {
	return xxx_messageInfo_EntityWithIndexes.Size(m)
}
func (m *EntityWithIndexes) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityWithIndexes.DiscardUnknown(m)
}

var xxx_messageInfo_EntityWithIndexes proto.InternalMessageInfo

func (m *EntityWithIndexes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EntityWithIndexes) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *EntityWithIndexes) GetRequiredExternalIds() []string {
	if m != nil {
		return m.RequiredExternalIds
	}
	return nil
}

func (m *EntityWithIndexes) GetOptionalExternalIds() []string {
	if m != nil {
		return m.OptionalExternalIds
	}
	return nil
}

func (m *EntityWithIndexes) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// EntityWithIndexesList
type EntityWithIndexesList struct {
	Items                []*EntityWithIndexes `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *EntityWithIndexesList) Reset()         { *m = EntityWithIndexesList{} }
func (m *EntityWithIndexesList) String() string { return proto.CompactTextString(m) }
func (*EntityWithIndexesList) ProtoMessage()    {}
func (*EntityWithIndexesList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22c1b92282e067, []int{1}
}

func (m *EntityWithIndexesList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityWithIndexesList.Unmarshal(m, b)
}
func (m *EntityWithIndexesList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityWithIndexesList.Marshal(b, m, deterministic)
}
func (m *EntityWithIndexesList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityWithIndexesList.Merge(m, src)
}
func (m *EntityWithIndexesList) XXX_Size() int {
	return xxx_messageInfo_EntityWithIndexesList.Size(m)
}
func (m *EntityWithIndexesList) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityWithIndexesList.DiscardUnknown(m)
}

var xxx_messageInfo_EntityWithIndexesList proto.InternalMessageInfo

func (m *EntityWithIndexesList) GetItems() []*EntityWithIndexes {
	if m != nil {
		return m.Items
	}
	return nil
}

// CreateEntityEntityWithIndexes
type CreateEntityEntityWithIndexes struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// one external id
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// required multiple external ids (minimum 1)
	RequiredExternalIds []string `protobuf:"bytes,3,rep,name=required_external_ids,json=requiredExternalIds,proto3" json:"required_external_ids,omitempty"`
	// optional multiple external ids (minimum 0)
	OptionalExternalIds  []string `protobuf:"bytes,4,rep,name=optional_external_ids,json=optionalExternalIds,proto3" json:"optional_external_ids,omitempty"`
	Value                int32    `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEntityEntityWithIndexes) Reset()         { *m = CreateEntityEntityWithIndexes{} }
func (m *CreateEntityEntityWithIndexes) String() string { return proto.CompactTextString(m) }
func (*CreateEntityEntityWithIndexes) ProtoMessage()    {}
func (*CreateEntityEntityWithIndexes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd22c1b92282e067, []int{2}
}

func (m *CreateEntityEntityWithIndexes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEntityEntityWithIndexes.Unmarshal(m, b)
}
func (m *CreateEntityEntityWithIndexes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEntityEntityWithIndexes.Marshal(b, m, deterministic)
}
func (m *CreateEntityEntityWithIndexes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEntityEntityWithIndexes.Merge(m, src)
}
func (m *CreateEntityEntityWithIndexes) XXX_Size() int {
	return xxx_messageInfo_CreateEntityEntityWithIndexes.Size(m)
}
func (m *CreateEntityEntityWithIndexes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEntityEntityWithIndexes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEntityEntityWithIndexes proto.InternalMessageInfo

func (m *CreateEntityEntityWithIndexes) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateEntityEntityWithIndexes) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *CreateEntityEntityWithIndexes) GetRequiredExternalIds() []string {
	if m != nil {
		return m.RequiredExternalIds
	}
	return nil
}

func (m *CreateEntityEntityWithIndexes) GetOptionalExternalIds() []string {
	if m != nil {
		return m.OptionalExternalIds
	}
	return nil
}

func (m *CreateEntityEntityWithIndexes) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*EntityWithIndexes)(nil), "schema.EntityWithIndexes")
	proto.RegisterType((*EntityWithIndexesList)(nil), "schema.EntityWithIndexesList")
	proto.RegisterType((*CreateEntityEntityWithIndexes)(nil), "schema.CreateEntityEntityWithIndexes")
}

func init() { proto.RegisterFile("with_indexes.proto", fileDescriptor_fd22c1b92282e067) }

var fileDescriptor_fd22c1b92282e067 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xc9, 0xae, 0x5b, 0xe8, 0x14, 0x04, 0xa3, 0x85, 0x78, 0x10, 0xc3, 0x9e, 0x72, 0x5a,
	0xa1, 0x3e, 0x82, 0x14, 0x2c, 0x78, 0xca, 0xc5, 0xe3, 0x12, 0xcd, 0xc0, 0x0e, 0xb4, 0x9b, 0x9a,
	0x4c, 0xb5, 0xbe, 0x9e, 0x0f, 0xe0, 0x33, 0x49, 0x1b, 0x56, 0x2a, 0xfb, 0x04, 0x1e, 0x67, 0xfe,
	0xef, 0x3b, 0xfc, 0x33, 0x20, 0x3f, 0x88, 0xbb, 0x96, 0x7a, 0x8f, 0x7b, 0x4c, 0xcd, 0x36, 0x06,
	0x0e, 0x72, 0x92, 0x5e, 0x3b, 0xdc, 0xb8, 0xfa, 0x4b, 0xc0, 0xc5, 0xb2, 0x67, 0xe2, 0xcf, 0x67,
	0xe2, 0x6e, 0x95, 0x19, 0x79, 0x0e, 0x05, 0x79, 0x25, 0xb4, 0x30, 0x53, 0x5b, 0x90, 0x97, 0xb7,
	0x30, 0xc3, 0x3d, 0x63, 0xec, 0xdd, 0xba, 0x25, 0xaf, 0x8a, 0x63, 0x00, 0xc3, 0x6a, 0xe5, 0xe5,
	0x02, 0xe6, 0x11, 0xdf, 0x76, 0x14, 0xd1, 0xb7, 0x27, 0x64, 0x52, 0xa5, 0x2e, 0xcd, 0xd4, 0x5e,
	0x0e, 0xe1, 0xf2, 0x57, 0x49, 0x07, 0x27, 0x6c, 0x99, 0xc2, 0x01, 0xfd, 0xe3, 0x9c, 0x65, 0x67,
	0x08, 0x4f, 0x9d, 0x2b, 0xa8, 0xde, 0xdd, 0x7a, 0x87, 0xaa, 0xd2, 0xc2, 0x54, 0x36, 0x0f, 0xf5,
	0x23, 0xcc, 0x47, 0x1d, 0x9e, 0x28, 0xb1, 0xbc, 0x83, 0x8a, 0x18, 0x37, 0x49, 0x09, 0x5d, 0x9a,
	0xd9, 0xe2, 0xba, 0xc9, 0xad, 0x9b, 0x11, 0x6d, 0x33, 0x57, 0x7f, 0x0b, 0xb8, 0x79, 0x88, 0xe8,
	0x18, 0x33, 0xf2, 0xdf, 0x4f, 0xf3, 0x32, 0x39, 0xbe, 0xfb, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff,
	0xa1, 0x53, 0x9f, 0x45, 0x04, 0x02, 0x00, 0x00,
}
