// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: erc20_service/erc20.proto

package erc20_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *NameResponse) Validate() error {
	return nil
}
func (this *SymbolResponse) Validate() error {
	return nil
}
func (this *DecimalsResponse) Validate() error {
	return nil
}
func (this *TotalSupplyResponse) Validate() error {
	return nil
}
func (this *BalanceOfRequest) Validate() error {
	return nil
}
func (this *BalanceOfResponse) Validate() error {
	return nil
}
func (this *TransferRequest) Validate() error {
	return nil
}
func (this *TransferResponse) Validate() error {
	return nil
}
func (this *AllowanceRequest) Validate() error {
	return nil
}
func (this *AllowanceResponse) Validate() error {
	return nil
}
func (this *ApproveRequest) Validate() error {
	return nil
}
func (this *ApproveResponse) Validate() error {
	return nil
}
func (this *TransferFromRequest) Validate() error {
	return nil
}
func (this *TransferEvent) Validate() error {
	return nil
}
func (this *ApprovalEvent) Validate() error {
	return nil
}
