// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: cpaper_proxy/cpaper_proxy.proto

package cpaper_proxy

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuer      string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	PaperNumber string `protobuf:"bytes,2,opt,name=paper_number,json=paperNumber,proto3" json:"paper_number,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpaper_proxy_cpaper_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_cpaper_proxy_cpaper_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_cpaper_proxy_cpaper_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *Id) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Id) GetPaperNumber() string {
	if x != nil {
		return x.PaperNumber
	}
	return ""
}

type InfoFromCPaper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuer      string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	PaperNumber string `protobuf:"bytes,2,opt,name=paper_number,json=paperNumber,proto3" json:"paper_number,omitempty"`
	Owner       string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *InfoFromCPaper) Reset() {
	*x = InfoFromCPaper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpaper_proxy_cpaper_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoFromCPaper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoFromCPaper) ProtoMessage() {}

func (x *InfoFromCPaper) ProtoReflect() protoreflect.Message {
	mi := &file_cpaper_proxy_cpaper_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoFromCPaper.ProtoReflect.Descriptor instead.
func (*InfoFromCPaper) Descriptor() ([]byte, []int) {
	return file_cpaper_proxy_cpaper_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *InfoFromCPaper) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *InfoFromCPaper) GetPaperNumber() string {
	if x != nil {
		return x.PaperNumber
	}
	return ""
}

func (x *InfoFromCPaper) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

var File_cpaper_proxy_cpaper_proxy_proto protoreflect.FileDescriptor

var file_cpaper_proxy_cpaper_proxy_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x63,
	0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x15, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75,
	0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x70, 0x65, 0x72, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x61, 0x0a, 0x0e, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x72, 0x6f,
	0x6d, 0x43, 0x50, 0x61, 0x70, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x70, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x32, 0x90, 0x01, 0x0a, 0x12, 0x43, 0x50, 0x61,
	0x70, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x7a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x50, 0x61, 0x70, 0x65, 0x72,
	0x12, 0x19, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x70, 0x61, 0x70,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x49, 0x64, 0x1a, 0x25, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x63, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x50, 0x61, 0x70,
	0x65, 0x72, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x12, 0x1f, 0x2f, 0x63, 0x70, 0x61,
	0x70, 0x65, 0x72, 0x2f, 0x7b, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x7d, 0x2f, 0x7b, 0x70, 0x61,
	0x70, 0x65, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x7d, 0x42, 0x32, 0x5a, 0x30, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x37, 0x74, 0x65, 0x63, 0x68,
	0x6c, 0x61, 0x62, 0x2f, 0x63, 0x63, 0x6b, 0x69, 0x74, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x2f, 0x63, 0x70, 0x61, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cpaper_proxy_cpaper_proxy_proto_rawDescOnce sync.Once
	file_cpaper_proxy_cpaper_proxy_proto_rawDescData = file_cpaper_proxy_cpaper_proxy_proto_rawDesc
)

func file_cpaper_proxy_cpaper_proxy_proto_rawDescGZIP() []byte {
	file_cpaper_proxy_cpaper_proxy_proto_rawDescOnce.Do(func() {
		file_cpaper_proxy_cpaper_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_cpaper_proxy_cpaper_proxy_proto_rawDescData)
	})
	return file_cpaper_proxy_cpaper_proxy_proto_rawDescData
}

var file_cpaper_proxy_cpaper_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cpaper_proxy_cpaper_proxy_proto_goTypes = []interface{}{
	(*Id)(nil),             // 0: examples.cpaper_proxy.Id
	(*InfoFromCPaper)(nil), // 1: examples.cpaper_proxy.InfoFromCPaper
}
var file_cpaper_proxy_cpaper_proxy_proto_depIdxs = []int32{
	0, // 0: examples.cpaper_proxy.CPaperProxyService.GetFromCPaper:input_type -> examples.cpaper_proxy.Id
	1, // 1: examples.cpaper_proxy.CPaperProxyService.GetFromCPaper:output_type -> examples.cpaper_proxy.InfoFromCPaper
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cpaper_proxy_cpaper_proxy_proto_init() }
func file_cpaper_proxy_cpaper_proxy_proto_init() {
	if File_cpaper_proxy_cpaper_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cpaper_proxy_cpaper_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cpaper_proxy_cpaper_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoFromCPaper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cpaper_proxy_cpaper_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cpaper_proxy_cpaper_proxy_proto_goTypes,
		DependencyIndexes: file_cpaper_proxy_cpaper_proxy_proto_depIdxs,
		MessageInfos:      file_cpaper_proxy_cpaper_proxy_proto_msgTypes,
	}.Build()
	File_cpaper_proxy_cpaper_proxy_proto = out.File
	file_cpaper_proxy_cpaper_proxy_proto_rawDesc = nil
	file_cpaper_proxy_cpaper_proxy_proto_goTypes = nil
	file_cpaper_proxy_cpaper_proxy_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CPaperProxyServiceClient is the client API for CPaperProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CPaperProxyServiceClient interface {
	// List method returns all registered commercial papers
	GetFromCPaper(ctx context.Context, in *Id, opts ...grpc.CallOption) (*InfoFromCPaper, error)
}

type cPaperProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCPaperProxyServiceClient(cc grpc.ClientConnInterface) CPaperProxyServiceClient {
	return &cPaperProxyServiceClient{cc}
}

func (c *cPaperProxyServiceClient) GetFromCPaper(ctx context.Context, in *Id, opts ...grpc.CallOption) (*InfoFromCPaper, error) {
	out := new(InfoFromCPaper)
	err := c.cc.Invoke(ctx, "/examples.cpaper_proxy.CPaperProxyService/GetFromCPaper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CPaperProxyServiceServer is the server API for CPaperProxyService service.
type CPaperProxyServiceServer interface {
	// List method returns all registered commercial papers
	GetFromCPaper(context.Context, *Id) (*InfoFromCPaper, error)
}

// UnimplementedCPaperProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCPaperProxyServiceServer struct {
}

func (*UnimplementedCPaperProxyServiceServer) GetFromCPaper(context.Context, *Id) (*InfoFromCPaper, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFromCPaper not implemented")
}

func RegisterCPaperProxyServiceServer(s *grpc.Server, srv CPaperProxyServiceServer) {
	s.RegisterService(&_CPaperProxyService_serviceDesc, srv)
}

func _CPaperProxyService_GetFromCPaper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CPaperProxyServiceServer).GetFromCPaper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.cpaper_proxy.CPaperProxyService/GetFromCPaper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CPaperProxyServiceServer).GetFromCPaper(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _CPaperProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "examples.cpaper_proxy.CPaperProxyService",
	HandlerType: (*CPaperProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFromCPaper",
			Handler:    _CPaperProxyService_GetFromCPaper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cpaper_proxy/cpaper_proxy.proto",
}
